name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Validate secrets
      shell: bash
      env:
        ORG_GRADLE_PROJECT_signingKey: '${{ secrets.SIGNING_KEY }}'
        ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.SIGNING_KEY_ID }}
        ORG_GRADLE_PROJECT_signingPassword: '${{ secrets.SIGNING_KEY_SECRET }}'
      run: echo $ORG_GRADLE_PROJECT_signingKey > k1 && cat k1
    - name: Build with Gradle
      env:
        ORG_GRADLE_PROJECT_signingKey: '${{ secrets.SIGNING_KEY }}'
        ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.SIGNING_KEY_ID }}
        ORG_GRADLE_PROJECT_signingPassword: '${{ secrets.SIGNING_KEY_SECRET }}'
      run: ./gradlew build --stacktrace
